# 1.	Write a Python Program to Add Two Matrices?


In [1]:
import numpy as np

matr1 = np.arange(8).reshape(2,4)
matr2 = np.random.randint(1,17,8).reshape(2,4)
print(matr1,"\n")
print(matr2,"\n")


print(np.add(matr1,matr2))






[[0 1 2 3]
 [4 5 6 7]] 

[[ 7  4 12 16]
 [ 9  6  7 10]] 

[[ 7  5 14 19]
 [13 11 13 17]]


# 2.	Write a Python Program to Multiply Two Matrices?


In [2]:

print(np.multiply(matr1,matr2))

[[ 0  4 24 48]
 [36 30 42 70]]


# 3.	Write a Python Program to Transpose a Matrix?


In [5]:
print(matr1.T)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


# 4.	Write a Python Program to Sort Words in Alphabetic Order?



In [4]:
l1 = ['tom','dick','harry','dom','ben','john']
print(sorted(l1))

['ben', 'dick', 'dom', 'harry', 'john', 'tom']


# 5.	Write a Python Program to Remove Punctuation From a String?

In [6]:
s='Hello my name is Sahil, i am 22 years old. I live in Mumbai, and i am learning data science from INeuron.ai'

''.join(s.split(','))

'Hello my name is Sahil i am 22 years old. I live in Mumbai and i am learning data science from INeuron.ai'